version: '3'

services:
  # Service for NodeJS API
  api:
    build: ./api
    # restart: unless-stopped
    container_name: api_backend
    # command: npm install
    # command: npm run dev
    volumes:
      - ./api/:/app
      - ./app/node_modules
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  # Service for React Client
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  # Service for Postgres Database
  postgres:
    image: postgres
    container_name: db_postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # Postgres port 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
